[package]
name = "iced_forms"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/walker84837/iced_forms"
description = "for future use (wip library for creating forms with iced)"
authors = ["walker84837"]

[dependencies]
